### ISSUE TITLE
实时性怎么样？

### ISSUE THREAD

**Issue by maomao0220** [Kin-Zhang/octomap#1]

**Comment by Kin-Zhang** [comment]
运行速度在README的图里有，特此再次复制到这里，对KITTI64线数据，平均1.86s/帧

![](https://raw.githubusercontent.com/Kin-Zhang/octomap/feat/benchmark/assets/imgs/demo.png)

如果你对实时性的要求是指10Hz 100ms每帧的处理速度的话，建议阅读：https://github.com/KTH-RPL/dufomap
